site_name: Binary Image Labelling

theme:
  name: "material"

plugins:
- mkdocstrings:
    default_handler: python

nav:
  - Organization Home: https://spatiotemporal-wildlife-classification.github.io/
  - Home: index.md
  - Code Documentation: code.md
